---

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    allow:
      - dependency-type: all
    groups:
      sentry:
        patterns:
          - "sentry*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
