---

ci:
  skip:
    - cargo-check
    - rustfmt
    - clippy

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Filesystem
      - id: check-case-conflict
      - id: check-symlinks
      # Whitespace
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # Syntax
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-sort-keys
      - id: check-toml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2
        types: [html]
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        language: system
        entry: cargo +stable check
        types: [rust]
        pass_filenames: false
      - id: rustfmt
        name: rustfmt
        language: system
        entry: cargo +nightly fmt
        types: [rust]
        args: ["--"]
      - id: clippy
        name: clippy
        language: system
        entry: cargo +stable clippy -- -D warnings
        types: [rust]
        pass_filenames: false
