[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
axum = { version = "0.6.1", features = ["macros"] }
axum-extra = { version = "0.4.2", features = ["cookie-private"] }
chrono = { version = "0.4.23", features = ["serde"] }
chrono-humanize = "0.2.2"
dotenvy = "0.15.6"
envy = "0.4.2"
futures = "0.3.25"
git-version = "0.3.5"
hyper = "0.14.23"
include_dir = "0.7.3"
mime_guess = "2.0.4"
minijinja = { version = "0.26.0", features = ["source"] }
once_cell = "1.16.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["json"] }
sentry = { version = "0.29.1", features = ["tracing", "tower"] }
sentry-tower = { version = "0.29.0", features = ["http"] }
sentry-tracing = "0.29.1"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["catch-panic", "trace", "fs", "compression-full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }

[dev-dependencies]
mockito = "0.31.0"
rstest = "0.16.0"
similar-asserts = "1.4.2"
