[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["macros"] }
axum-extra = { version = "0.7.4", features = ["cookie-private"] }
chrono = { version = "0.4.26", features = ["serde"] }
chrono-humanize = "0.2.2"
dotenvy = "0.15.7"
envy = "0.4.2"
futures = "0.3.28"
git-version = "0.3.5"
hyper = "0.14.27"
include_dir = "0.7.3"
mime_guess = "2.0.4"
minijinja = { version = "0.34.0", features = ["source"] }
once_cell = "1.18.0"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
sentry = { version = "0.31.5", features = ["tracing", "tower", "tower-axum-matched-path", "tower-http"] }
sentry-tower = { version = "0.31.3", features = ["http", "axum-matched-path"] }
sentry-tracing = "0.31.3"
serde = { version = "1.0.168", features = ["derive"] }
serde_json = "1.0.102"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["catch-panic", "trace", "fs", "compression-full"] }
tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt"] }

[dev-dependencies]
mockito = "1.1.0"
rstest = "0.18.1"
similar-asserts = "1.4.2"

[profile.release]
# Enable line numbers in Sentry
debug = 1
