[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.11"
axum-extra = { version = "0.3.6", features = ["cookie-private"] }
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
dotenvy = "0.15.1"
envy = "0.4.2"
git-version = "0.3.5"
hyper = "0.14.19"
once_cell = "1.13.0"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["json"] }
sentry = { version = "0.27.0", features = ["tracing", "tower"] }
sentry-tower = "0.27.0"
sentry-tracing = "0.27.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tera = "1.16.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["catch-panic", "trace", "fs", "compression-full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "fmt"] }

[dev-dependencies]
mockito = "0.31.0"
pretty_assertions = "1.2.1"
rstest = "0.15.0"
