[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.64"
axum = "0.5.15"
axum-extra = { version = "0.3.7", features = ["cookie-private"] }
chrono = { version = "0.4.22", features = ["serde"] }
chrono-humanize = "0.2.2"
dotenvy = "0.15.3"
envy = "0.4.2"
futures = "0.3.23"
git-version = "0.3.5"
hyper = "0.14.20"
include_dir = "0.7.2"
mime_guess = "2.0.4"
minijinja = { version = "0.20.0", features = ["source"] }
once_cell = "1.14.0"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["json"] }
sentry = { version = "0.27.0", features = ["tracing", "tower"] }
sentry-tower = { version = "0.27.0", features = ["http"] }
sentry-tracing = "0.27.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["catch-panic", "trace", "fs", "compression-full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "fmt"] }

[dev-dependencies]
mockito = "0.31.0"
rstest = "0.15.0"
similar-asserts = "1.4.2"
