[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.11"
chrono = "0.4.19"
dotenvy = "0.15.1"
hyper = "0.14.19"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["catch-panic", "trace", "fs"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "fmt"] }

[dev-dependencies]
mockito = "0.31.0"
once_cell = "1.13.0"
pretty_assertions = "1.2.1"
rstest = "0.15.0"
