[package]
name = "wanikani-apprentice"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.1"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["fmt"] }

[dev-dependencies]
mockito = "0.31.0"
pretty_assertions = "1.2.1"
rstest = "0.15.0"
