app = "wanikani-apprentice"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[env]
  DEBUG = "false"
  WEB_CONCURRENCY = "2"
  SENTRY_ENABLED = "true"
  SENTRY_DSN = "https://64dfba28156a490999df043f193cfcd3@o1059726.ingest.sentry.io/6048576"
  SENTRY_ENVIRONMENT = "prod"
  HTTPS_ONLY = "true"
  TRUSTED_HOSTS = "wk-apprentice.rouge8.com"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[statics]]
  guest_path = "/app/src/wanikani_apprentice/static"
  url_prefix = "/static"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "10s"
    interval = "10s"
    method = "get"
    path = "/login"
    protocol = "http"
    timeout = "2s"
