app = "wanikani-apprentice"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[env]
  DEBUG = "false"
  WEB_CONCURRENCY = "2"
  SENTRY_ENABLED = "true"
  SENTRY_ENVIRONMENT = "prod"
  HTTPS_ONLY = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "10s"
    timeout = "2s"
