---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tox:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    env:
      TOXENV: ${{ matrix.toxenv }}

    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py310
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ matrix.toxenv }}
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox
      - name: tox
        run: python -m tox

  pip-compile:
    name: pip-compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-compile
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox
      - name: tox
        # Verify requirements.txt is up to date
        run: python -m tox -e pip-compile && git diff --exit-code
