---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tox:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    env:
      TOXENV: ${{ matrix.toxenv }}

    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py310
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Generate the cache suffix
        id: cache-suffix
        run: |
          echo ::set-output name=cache-suffix::${TOXENV//,/-}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
            .mypy_cache
          key: ${{ runner.os }}-pip-${{ steps.cache-suffix.outputs.cache-suffix }}
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox
      - name: tox
        run: python -m tox

  pip-compile:
    name: pip-compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-compile
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox
      - name: tox
        # Verify requirements.txt is up to date
        run: python -m tox -e pip-compile && git diff --exit-code

  deploy:
    name: Deploy
    needs: [tox, pip-compile]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    environment:
      name: prod
      url: https://wk-apprentice.rouge8.com
    concurrency: prod
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          DOCKER_BUILDKIT: 1
        with:
          args: deploy
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: rouge8
          SENTRY_PROJECT: wanikani-apprentice
        with:
          environment: prod
