---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --no-fail-fast

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  deploy:
    name: Deploy
    needs:
      - build-and-test
      - pre-commit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    environment:
      name: prod
      url: https://wk-apprentice.rouge8.com
    concurrency: prod
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        env:
          DOCKER_BUILDKIT: 1
        with:
          args: deploy
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: rouge8
          SENTRY_PROJECT: wanikani-apprentice
        with:
          environment: prod
